package flow.pkg4;

import java.awt.Color;

public class Flow4GUI extends javax.swing.JFrame {

    private WordPairControlIF control;
    
    public Flow4GUI(WordPairControlIF control) {
        initComponents();
        this.control = control;
        initializeProgram();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        translatePanel = new javax.swing.JPanel();
        danskTranslateLabel = new javax.swing.JLabel();
        danskTranslateField = new javax.swing.JTextField();
        engelskTranslateLabel = new javax.swing.JLabel();
        engelskTranslateField = new javax.swing.JTextField();
        danskTranslateButton = new javax.swing.JButton();
        engelskTranslateButton = new javax.swing.JButton();
        questionPanel = new javax.swing.JPanel();
        explainQuizLabel = new javax.swing.JLabel();
        questionQuizButton = new javax.swing.JButton();
        word1QuizLabel = new javax.swing.JLabel();
        word2QuizLabel = new javax.swing.JLabel();
        guessQuizField = new javax.swing.JTextField();
        guess1QuizLabel = new javax.swing.JLabel();
        guess2QuizLabel = new javax.swing.JLabel();
        guessQuizButton = new javax.swing.JButton();
        addPanel = new javax.swing.JPanel();
        danskAddLabel = new javax.swing.JLabel();
        danskAddField = new javax.swing.JTextField();
        engelskAddLabel = new javax.swing.JLabel();
        engelskAddField = new javax.swing.JTextField();
        wordAddButton = new javax.swing.JButton();
        deleteAddButton = new javax.swing.JButton();
        counterAddLabel = new javax.swing.JLabel();
        helpGlobalLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Language Trainer");
        setMinimumSize(new java.awt.Dimension(200, 150));
        setPreferredSize(new java.awt.Dimension(640, 480));
        setResizable(false);

        danskTranslateLabel.setText("Danish");

        engelskTranslateLabel.setText("English");

        danskTranslateButton.setText("Translate");
        danskTranslateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                danskTranslateButtonActionPerformed(evt);
            }
        });

        engelskTranslateButton.setText("Translate");
        engelskTranslateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engelskTranslateButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout translatePanelLayout = new org.jdesktop.layout.GroupLayout(translatePanel);
        translatePanel.setLayout(translatePanelLayout);
        translatePanelLayout.setHorizontalGroup(
            translatePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(translatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(translatePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(danskTranslateField)
                    .add(engelskTranslateField)
                    .add(translatePanelLayout.createSequentialGroup()
                        .add(translatePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(danskTranslateLabel)
                            .add(danskTranslateButton)
                            .add(engelskTranslateLabel)
                            .add(engelskTranslateButton))
                        .add(0, 518, Short.MAX_VALUE)))
                .addContainerGap())
        );
        translatePanelLayout.setVerticalGroup(
            translatePanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(translatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(danskTranslateLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(danskTranslateField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(danskTranslateButton)
                .add(18, 18, 18)
                .add(engelskTranslateLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(engelskTranslateField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(engelskTranslateButton)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Translate", translatePanel);

        explainQuizLabel.setText("Can you guess the danish equivalent of the word?");

        questionQuizButton.setText("New Question");
        questionQuizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                questionQuizButtonActionPerformed(evt);
            }
        });

        word1QuizLabel.setText("The Word:");

        guess1QuizLabel.setText("Were you correct?");

        guessQuizButton.setText("Make quess");
        guessQuizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessQuizButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout questionPanelLayout = new org.jdesktop.layout.GroupLayout(questionPanel);
        questionPanel.setLayout(questionPanelLayout);
        questionPanelLayout.setHorizontalGroup(
            questionPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(questionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(questionPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(guessQuizField)
                    .add(questionPanelLayout.createSequentialGroup()
                        .add(questionPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(explainQuizLabel)
                            .add(questionQuizButton)
                            .add(guessQuizButton))
                        .add(0, 354, Short.MAX_VALUE))
                    .add(questionPanelLayout.createSequentialGroup()
                        .add(guess1QuizLabel)
                        .add(18, 18, 18)
                        .add(guess2QuizLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(questionPanelLayout.createSequentialGroup()
                        .add(word1QuizLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(word2QuizLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        questionPanelLayout.setVerticalGroup(
            questionPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(questionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(explainQuizLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(questionQuizButton)
                .add(18, 18, 18)
                .add(questionPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(word1QuizLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(word2QuizLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(guessQuizField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(guessQuizButton)
                .add(18, 18, 18)
                .add(questionPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(guess1QuizLabel)
                    .add(guess2QuizLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(217, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quiz", questionPanel);

        danskAddLabel.setText("Danish");

        danskAddField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                danskAddFieldActionPerformed(evt);
            }
        });

        engelskAddLabel.setText("English");

        wordAddButton.setText("Add Words");
        wordAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wordAddButtonActionPerformed(evt);
            }
        });

        deleteAddButton.setText("Delete Words");
        deleteAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAddButtonActionPerformed(evt);
            }
        });

        counterAddLabel.setText("Kan du se det her, er der noget galt.");

        org.jdesktop.layout.GroupLayout addPanelLayout = new org.jdesktop.layout.GroupLayout(addPanel);
        addPanel.setLayout(addPanelLayout);
        addPanelLayout.setHorizontalGroup(
            addPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(addPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(engelskAddField)
                    .add(addPanelLayout.createSequentialGroup()
                        .add(addPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(danskAddLabel)
                            .add(engelskAddLabel)
                            .add(addPanelLayout.createSequentialGroup()
                                .add(wordAddButton)
                                .add(18, 18, 18)
                                .add(deleteAddButton))
                            .add(counterAddLabel))
                        .add(0, 395, Short.MAX_VALUE))
                    .add(danskAddField))
                .addContainerGap())
        );
        addPanelLayout.setVerticalGroup(
            addPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(addPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(danskAddLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(danskAddField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(engelskAddLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(engelskAddField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(addPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(wordAddButton)
                    .add(deleteAddButton))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 220, Short.MAX_VALUE)
                .add(counterAddLabel)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Add Word", addPanel);

        helpGlobalLabel.setText("Help is here!");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(layout.createSequentialGroup()
                        .add(helpGlobalLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 257, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(helpGlobalLabel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void danskAddFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_danskAddFieldActionPerformed

    }//GEN-LAST:event_danskAddFieldActionPerformed

    private void deleteAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAddButtonActionPerformed
        if(control.delete(danskAddField.getText())){
            helpGlobalLabel.setText("'" + danskAddField.getText() + "' has been removed from the list of words.");
            danskAddField.setText("");
            engelskAddField.setText("");
            counterAddLabel.setText(control.size() + " words");
            control.save();
        } else {
            helpGlobalLabel.setText("'" + danskAddField.getText() + "' could not be found on the list of words.");
        }
    }//GEN-LAST:event_deleteAddButtonActionPerformed

    private void wordAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wordAddButtonActionPerformed
        control.add(danskAddField.getText(), engelskAddField.getText());
        helpGlobalLabel.setText("'" + danskAddField.getText() + "' has been added to the list of words.");
        danskAddField.setText("");
        engelskAddField.setText("");
        counterAddLabel.setText(control.size() + " words");
        control.save();
    }//GEN-LAST:event_wordAddButtonActionPerformed

    private void danskTranslateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_danskTranslateButtonActionPerformed
        String test = control.lookup(danskTranslateField.getText());
        if (test != null){
            engelskTranslateField.setText(test);
        } else {
            helpGlobalLabel.setText("'" + danskTranslateField.getText() + "' could not be found on the list of words.");
        }
    }//GEN-LAST:event_danskTranslateButtonActionPerformed

    private void engelskTranslateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engelskTranslateButtonActionPerformed
        String test = control.lookup(engelskTranslateField.getText());
        if (test != null){
            danskTranslateField.setText(test);
        } else {
            helpGlobalLabel.setText("'" + engelskTranslateField.getText() + "' could not be found on the list of words.");
        }
    }//GEN-LAST:event_engelskTranslateButtonActionPerformed

    private void questionQuizButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_questionQuizButtonActionPerformed
        String add = control.getRandomQuestion();
        if (add != null){
            word2QuizLabel.setText(add);
        } else {
            helpGlobalLabel.setText("No words could be found in the list.");
        }
    }//GEN-LAST:event_questionQuizButtonActionPerformed

    private void guessQuizButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessQuizButtonActionPerformed
        if (control.checkGuess(word2QuizLabel.getText(), guessQuizField.getText())){
            guess2QuizLabel.setForeground(Color.green);
            guess2QuizLabel.setText("Correct!");
        } else {
            guess2QuizLabel.setForeground(Color.red);
            guess2QuizLabel.setText("Wrong!");
        }
    }//GEN-LAST:event_guessQuizButtonActionPerformed

    private void initializeProgram(){
        if(control.load()){
            helpGlobalLabel.setText("List found and loaded.");
        } else {
            helpGlobalLabel.setText("Could not find list.");
        }
        counterAddLabel.setText(control.size() + " words");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addPanel;
    private javax.swing.JLabel counterAddLabel;
    private javax.swing.JTextField danskAddField;
    private javax.swing.JLabel danskAddLabel;
    private javax.swing.JButton danskTranslateButton;
    private javax.swing.JTextField danskTranslateField;
    private javax.swing.JLabel danskTranslateLabel;
    private javax.swing.JButton deleteAddButton;
    private javax.swing.JTextField engelskAddField;
    private javax.swing.JLabel engelskAddLabel;
    private javax.swing.JButton engelskTranslateButton;
    private javax.swing.JTextField engelskTranslateField;
    private javax.swing.JLabel engelskTranslateLabel;
    private javax.swing.JLabel explainQuizLabel;
    private javax.swing.JLabel guess1QuizLabel;
    private javax.swing.JLabel guess2QuizLabel;
    private javax.swing.JButton guessQuizButton;
    private javax.swing.JTextField guessQuizField;
    private javax.swing.JLabel helpGlobalLabel;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel questionPanel;
    private javax.swing.JButton questionQuizButton;
    private javax.swing.JPanel translatePanel;
    private javax.swing.JLabel word1QuizLabel;
    private javax.swing.JLabel word2QuizLabel;
    private javax.swing.JButton wordAddButton;
    // End of variables declaration//GEN-END:variables
}
